version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS:PLAINTEXT:
      KAFKA_OFFSETS_TOPIC_APPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "asistencia_eventos:3:1,alertas_inasistencia:1:1,estadisticas_diarias:1:1"
    healthcheck:
      test:
        ["CMD", "kafka-topics", "--list", "--boostrap-server", "localhost:9092"]
      interval: 10s
      timeout: 30s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  asistencia-producer:
    build: .
    command: node asistencia-producer.js
    depends_on:
      - kafka
      - rabbitmq
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://rabbitmq

  asistencia-processor:
    build: .
    command: node asistencia-processor.js
    depends_on:
      - kafka
      - rabbitmq
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://rabbitmq

  asistencia-backend:
    build: .
    command: node asistencia-backend.js
    ports:
      - "8080:8080"

    depends_on:
      - asistencia-producer
      - asistencia-processor

    environment:
      API_PORT: 8080
