version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0      
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports: 
     - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "match_events:1:1"
    volumes: 
      - ./kafka/init-kafka.sh:/tmp/init-kafka.sh
    command: bash -c "sleep 10 && /tmp/init-kafka.sh && kafka-server-start /etc/kafka/server.properties"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes: 
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: rabbitmqctl status
      interval: 10s
      timeout: 5s
      retries: 10

  betting_api:
    build: ./betting_api
    command: node betting_api.js
    depends_on: 
      kafka: 
        condition: service_healthy
    ports:
      - "8080:8080"

  dashboard_backend:
    build: ./dashboard_backend
    command: node dashboard_backend.js
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    ports:
      - "8081:8081"
      - "8082:8082"


  match_generator:
    build: ./match_generator
    container_name: match_generator.js
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      MATCH_DURATION_MS: 300000
      CREATE_INTERVAL_MS: 10000
    depends_on:
      - kafka
      - rabbitmq

  match_simulator:
    build: ./match_simulator
    container_name: match_simulator.js
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    depends_on:
      - kafka
      - rabbitmq
